name = "abdu-academy"
compatibility_date = "2024-12-19"
compatibility_flags = ["nodejs_compat"]

[build]
command = "npm run build"
output_directory = "build"

[env.production]
name = "abdu-academy-production"

[env.staging]
name = "abdu-academy-staging"

[[redirects]]
from = "/*"
to = "/index.html"
status = 200

[site]
bucket = "./build"
